spring:
  profiles:
    include:
      - aws
    active: devdb
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

---

spring:
  profiles:
    group:
      "tony": "tonydb, common"
      "heather": "jindb,common"
      "dev": "devdb,common"

---

spring:
  config:
    activate:
      on-profile: "devdb"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://feverdb.cy76xlw8fwhe.ap-northeast-2.rds.amazonaws.com:3306/playcanival?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: fever
    password: fever1234
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: f5c10aa7e91298cd339126823d81edc9 # 카카오 디벨로퍼 REST API 키   클라이언트 ID
            redirect-uri: http://localhost:8080/oauth/kakao/callback #"{baseUrl}/{action}/oauth2/code/{registrationId}" # http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
---

spring:
  config:
    activate:
      on-profile: "jindb"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/testdb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: Jin
    password: Jin

---

spring:
  config:
    activate:
      on-profile: "tonydb"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/raonfever?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: gm040404@

---

spring:
  config:
    activate:
      on-profile: "common"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true


